const {JSDOM}=require('jsdom'),jquery=require('jquery'),fs=require('fs'),assert=require('node:assert/strict');
const dom=new JSDOM('<a id="cycle_next" href="#"></a><a id="cycle_prev" href="#"></a><a id="cycle_pause" href="#"></a><div id="wm_countdown"></div><div id="wm_progress"></div><span id="wm_current_map"></span><span id="wm_total_map"></span><div class="weathermapholder"><img src="a?time=0"></div><div class="weathermapholder"><img src="b?time=0"></div>',{runScripts:'outside-only',url:'https://example.test/'});
const w=dom.window,$=jquery(w);w.$=w.jQuery=$;$.fx.off=true;let reloadCallback;w.setInterval=()=>1;w.setTimeout=(fn)=>{reloadCallback=fn;return 2;};require('vm').runInContext(fs.readFileSync(require('node:path').join(__dirname,'../../js/map-cycle.js'),'utf8'),dom.getInternalVMContext());
const c=w.WMcycler;
c.start({period:0,poller_cycle:300000,fullscreen:0});const pageReload=reloadCallback;
assert.equal(c.period,150000);assert.equal(c.current,0);assert.equal($('#wm_countdown').text(),'Next map in 150s');assert.equal($('#wm_progress')[0].style.width,'100%');
c.nextAction();assert.equal(c.current,1);c.nextAction();assert.equal(c.current,0);c.previousAction();assert.equal(c.current,1);
c.countdown=500;c.updateProgress();assert.equal($('#wm_countdown').text(),'Next map in 100s');assert.ok(Math.abs(parseFloat($('#wm_progress')[0].style.width)-66.6667)<.01);
c.pauseAction();const paused=c.countdown;c.counterHandler();assert.equal(c.countdown,paused);assert.equal($('#wm_countdown').text(),'Paused');c.pauseAction();c.counterHandler();assert.equal(c.countdown,paused-1);
c.countdown=0;c.counterHandler();assert.equal(c.current,0);assert.equal(c.countdown,750);
let reloadUrl;w.loadPage=(url)=>reloadUrl=url;pageReload();assert.equal(reloadUrl,'https://example.test/');
c.period=30000;c.switchMap(0);assert.equal($('#wm_countdown').text(),'Next map in 30s');
c.countdown=-3;c.updateProgress();assert.equal($('#wm_progress')[0].style.width,'0%');
const src=fs.readFileSync(require('node:path').join(__dirname,'../../js/map-cycle.js'),'utf8');
const body=src.match(/this.timer_reloader = setTimeout\(function \(\) \{([\s\S]*?)\}, this.poller_cycle\);/)[1];
let fullReload=0;new Function('that','window','document',body)({fullscreen:1},{location:{reload(){fullReload++;}}},{location:{href:'x'}});assert.equal(fullReload,1);
$('#wm_countdown').attr('data-next-label','Following map: %s seconds').attr('data-paused-label','Waiting');c.updateProgress();assert.equal($('#wm_countdown').text(),'Following map: 0 seconds');c.pauseAction();assert.equal($('#wm_countdown').text(),'Waiting');c.pauseAction();
c.start({period:30000,poller_cycle:300000,fullscreen:0});c.start({period:30000,poller_cycle:300000,fullscreen:0});
$('#cycle_next').trigger('click');assert.equal(c.current,1);$(w.document).trigger($.Event('keyup',{keyCode:39}));assert.equal(c.current,0);
$('.weathermapholder').last().remove();c.start({period:0,poller_cycle:300000,fullscreen:0});assert.equal(c.period,300000);c.nextAction();assert.equal(c.current,0);
$('.weathermapholder').remove();c.start({period:0,poller_cycle:300000,fullscreen:0});assert.equal(c.nmaps,0);c.stop();
console.log('PASS: translated labels, repeated initialization, one/no-map cases, click/key navigation; automatic period, first countdown, next/previous wrap, pause/resume, automatic transition, progress bounds, configured period and fullscreen reload fallback');
